version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions:
          - "version-update:semver-major"
      - dependency-name: "System.*"
        versions:
          - "version-update:semver-major"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "microsoft/*"
        versions:
          - "version-update:semver-major"
