name: Publish Docker Images

on:
  push:
    tags:
      - "*"

jobs:
  chat-agent:
    name: Publish Chat Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Chat.Agent/Dockerfile
      image_name: floppybot/chat-agent
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  command-executor:
    name: Publish Command Executor Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@11-command-about
    with:
      dockerfile_path: src/FloppyBot.Commands.Executor.Agent/Dockerfile
      image_name: floppybot/command-executor
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  command-parser:
    name: Publish Command Parser Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Commands.Parser.Agent/Dockerfile
      image_name: floppybot/command-parser
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
