name: Publish Docker Images

on:
  push:
    tags:
      - "*"

jobs:
  chat-agent:
    name: Publish Chat Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Chat.Agent/Dockerfile
      project_path: src/FloppyBot.Chat.Agent/FloppyBot.Chat.Agent.csproj
      image_name: floppybot/chat-agent
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  command-executor:
    name: Publish Command Executor Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Commands.Executor.Agent/Dockerfile
      project_path: src/FloppyBot.Commands.Executor.Agent/FloppyBot.Commands.Executor.Agent.csproj
      image_name: floppybot/command-executor
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  command-parser:
    name: Publish Command Parser Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Commands.Parser.Agent/Dockerfile
      project_path: src/FloppyBot.Commands.Parser.Agent/FloppyBot.Commands.Parser.Agent.csproj
      image_name: floppybot/command-parser
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  message-counter:
    name: Publish Message Counter Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Aux.MessageCounter.Agent/Dockerfile
      project_path: src/FloppyBot.Aux.MessageCounter.Agent/FloppyBot.Aux.MessageCounter.Agent.csproj
      image_name: floppybot/message-counter
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  twitch-alerts:
    name: Publish Twitch Alert Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Aux.TwitchAlerts.Agent/Dockerfile
      project_path: src/FloppyBot.Aux.TwitchAlerts.Agent/FloppyBot.Aux.TwitchAlerts.Agent.csproj
      image_name: floppybot/twitch-alerts
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  webapi:
    name: Publish Web API Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.WebApi.Agent/Dockerfile
      project_path: src/FloppyBot.WebApi.Agent/FloppyBot.WebApi.Agent.csproj
      image_name: floppybot/web-api
      image_tag: ${{ github.ref_name }}
      push_latest: true
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
