name: Publish Command Executor Agent

on:
  push:
    tags:
      - "*"

jobs:
  release-docker-image:
    name: Publish Command Parser Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Commands.Executor.Agent/Dockerfile
      image_name: floppybot/command-executor
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
