name: Publish Chat Agent

on:
  push:
    tags:
      - "*"

jobs:
  release-docker-image:
    name: Publish Chat Agent
    uses: rGunti/FloppyBot/.github/workflows/template-release-docker-image.yml@main
    with:
      dockerfile_path: src/FloppyBot.Chat.Agent/Dockerfile
      image_name: floppybot/chat-agent
      image_tag: ${{ github.ref_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
