on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      dockerfile_context:
        required: false
        type: string
        default: "."
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      docker_hub_username:
        required: true
      docker_hub_token:
        required: true

jobs:
  build-docker-image:
    name: Build ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      # Setup Environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Build
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerfile_context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CODE_VERSION=${{ inputs.image_tag }}
